-- トランザクション明細テーブル
CREATE TABLE IF NOT EXISTS m_product_yama_dtl (
    DTL_ID INT AUTO_INCREMENT PRIMARY KEY,  -- AUTO_INCREMENTを追加
    TRD_ID INT NOT NULL,
    PRD_ID INT NOT NULL,
    PRD_CODE VARCHAR(13) NOT NULL,
    PRD_NAME VARCHAR(50) NOT NULL,
    PRD_PRICE INT NOT NULL,
    FOREIGN KEY (TRD_ID) REFERENCES m_product_yama_trd(TRD_ID)
); 